import { BottomNavbar } from "@/components/bottom-nav";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} flex flex-col`}>
				<section className="flex-end fixed py-4 top-0 w-full bg-secondary">
					header
				</section>
				<section className="my-16">{children}</section>
				<section className="flex-end fixed bottom-0 w-full bg-secondary">
					<BottomNavbar />
				</section>
			</body>
		</html>
	);
}
